name: Build Docker Image
description: Build Docker Image Action

outputs:
  image_name:
    description: Name of the built Docker image
    value: ${{ steps.build.outputs.image_name }}

runs:
  using: "composite"
  steps:
    # Checkout ar-image repository to get the Dockerfile
    - name: Checkout ar-image repo for Dockerfile
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        repository: Audioreach/ar-image

    - name: Build Docker Image
      shell: bash
      id: build
      run: |
        echo "::group::$(printf '__________ %-100s' 'build' | tr ' ' _)"
        docker build -t ar-image:latest --build-arg "USER=$(whoami)" --build-arg "UID=$(id -u)" --build-arg "GID=$(id -g)" -f Dockerfile .
        echo "::endgroup::"
        echo "Docker image ar-image:latest built successfully."
        echo "image_name=ar-image:latest" >> $GITHUB_OUTPUT

    # Checkout the main repo again for later steps
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.ref }}
